#!/usr/bin/env python3
import math
import rclpy
from rclpy.node import Node
from geometry_msgs.msg import Twist, TransformStamped
from nav_msgs.msg import Odometry
from std_msgs.msg import Float32MultiArray
from tf2_ros import TransformBroadcaster


def yaw_to_quaternion(yaw: float):
    half = yaw * 0.5
    return 0.0, 0.0, math.sin(half), math.cos(half)


class FakeOdom(Node):
    """Software-only odometry generated by integrating velocity commands.

    Replace this node with encoder-derived odometry when hardware is available.
    """

    def __init__(self) -> None:
        super().__init__("fake_odom")
        self.declare_parameter("cmd_topic", "/cmd_vel")
        self.declare_parameter("odom_topic", "/odom")
        self.declare_parameter("state_topic", "/vla/state")
        self.declare_parameter("odom_frame", "odom")
        self.declare_parameter("base_frame", "base_link")
        self.declare_parameter("publish_tf", False)
        self.declare_parameter("rate_hz", 30.0)
        self.declare_parameter("command_timeout_sec", 0.5)

        cmd_topic = str(self.get_parameter("cmd_topic").value)
        self.odom_topic = str(self.get_parameter("odom_topic").value)
        state_topic = str(self.get_parameter("state_topic").value)
        self.odom_frame = str(self.get_parameter("odom_frame").value)
        self.base_frame = str(self.get_parameter("base_frame").value)
        self.publish_tf = bool(self.get_parameter("publish_tf").value)
        rate = max(float(self.get_parameter("rate_hz").value), 1.0)
        self.command_timeout = max(float(self.get_parameter("command_timeout_sec").value), 0.05)

        self.create_subscription(Twist, cmd_topic, self.cmd_callback, 10)
        self.publisher = self.create_publisher(Odometry, self.odom_topic, 10)
        self.state_publisher = self.create_publisher(
            Float32MultiArray, state_topic, 10
        )
        self.tf_broadcaster = TransformBroadcaster(self) if self.publish_tf else None

        self.linear = 0.0
        self.angular = 0.0
        self.x = 0.0
        self.y = 0.0
        self.yaw = 0.0
        self.last_cmd_time = None
        self.last_update = self.get_clock().now()
        self.timer = self.create_timer(1.0 / rate, self.update)

    def cmd_callback(self, msg: Twist) -> None:
        self.linear = float(msg.linear.x)
        self.angular = float(msg.angular.z)
        self.last_cmd_time = self.get_clock().now()

    def update(self) -> None:
        now = self.get_clock().now()
        dt = max((now - self.last_update).nanoseconds / 1e9, 0.0)
        self.last_update = now

        stale = (
            self.last_cmd_time is None
            or (now - self.last_cmd_time).nanoseconds / 1e9 > self.command_timeout
        )
        linear = 0.0 if stale else self.linear
        angular = 0.0 if stale else self.angular

        self.x += linear * math.cos(self.yaw) * dt
        self.y += linear * math.sin(self.yaw) * dt
        self.yaw += angular * dt
        qx, qy, qz, qw = yaw_to_quaternion(self.yaw)

        msg = Odometry()
        msg.header.stamp = now.to_msg()
        msg.header.frame_id = self.odom_frame
        msg.child_frame_id = self.base_frame
        msg.pose.pose.position.x = self.x
        msg.pose.pose.position.y = self.y
        msg.pose.pose.orientation.x = qx
        msg.pose.pose.orientation.y = qy
        msg.pose.pose.orientation.z = qz
        msg.pose.pose.orientation.w = qw
        msg.twist.twist.linear.x = linear
        msg.twist.twist.angular.z = angular
        self.publisher.publish(msg)

        state = Float32MultiArray()
        state.data = [float(linear), float(angular)]
        self.state_publisher.publish(state)

        if self.tf_broadcaster is not None:
            transform = TransformStamped()
            transform.header = msg.header
            transform.child_frame_id = self.base_frame
            transform.transform.translation.x = self.x
            transform.transform.translation.y = self.y
            transform.transform.rotation = msg.pose.pose.orientation
            self.tf_broadcaster.sendTransform(transform)


def main(args=None) -> None:
    rclpy.init(args=args)
    node = FakeOdom()
    try:
        rclpy.spin(node)
    except KeyboardInterrupt:
        pass
    finally:
        node.destroy_node()
        if rclpy.ok():
            rclpy.shutdown()


if __name__ == "__main__":
    main()
